version: '3.8'

services:
  keycloak-docker:
    image: "quay.io/keycloak/keycloak:22.0.3"
    ports:
      - "8084:8080"
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

  mysql-docker:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqldb:/var/lib/mysql
  mongo-docker:
    image: "mongo:6-jammy"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - dbdata6:/data/db
  zipkin-docker:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
volumes:
  mysqldb:
  dbdata6:


